### PR TITLE
fix reference to team in emugroupmapping

### PR DESCRIPTION
**Pull request by tomasmota**
The reference to the team did not specify that the slug must be used instead of the ID, so teamSlugSelector and teamSlugRef did not work. I have fixed it and tested both of them.

Also fixed the placing of commends in external_name.go, which got messed up with the earlier rebase.

### CODE REVIEW

**Review by AtzeDeVries — APPROVED** [review]

**Comment by AtzeDeVries** [comment]
@tomasmota thanks! i see i did not properly check the previous PR is see. I just assumed the CI to be ok in this case.

**Comment by tomasmota** [comment]
yeah, let me know if I should do anything else before you can merge

**Comment by AtzeDeVries** [comment]
mm just trying to find out detect-noop is true (and thus not running any ci).

**Review by AtzeDeVries — APPROVED** [review]

**Comment by AtzeDeVries** [comment]
@tomasmota https://marketplace.upbound.io/providers/coopnorge/provider-github/v0.7.1

**Pull request merged**
