### PR TITLE
feat: add support for retry_delay_ms, max_retries, retryable_errors

### PR DESCRIPTION
**Pull request by lacroi-m-insta**
When a project secret is out of date and that you have a webhook resource the terraform provider spams github until rate limit. By adding the possibility to configure retry_delay_ms, max_retries and retryable_errors it is posisble to avoid this. I have tested this on my end with success by setting this:
```
{"owner":"lacroi-m-insta","token":"xxxx","write_delay_ms":60000,"read_delay_ms":60000,"retry_delay_ms":60000,"max_retries":1,"retryable_errors":[401]}
```
As the token of the matching secret.

These values are only available in the versions of TERRAFORM_PROVIDER_VERSION above 6.2.1

### CODE REVIEW

**Comment by AtzeDeVries** [comment]
I just merged https://github.com/coopnorge/provider-github/pull/80

This creates a lot of merge conflicts. This pr also updates the provider to 6.2.2.

**Comment by lacroi-m-insta** [comment]
@AtzeDeVries great it will make for a cleaner PR 😄 I've updated my repository it's ready now

**Comment by lacroi-m-insta** [comment]
I didnt see this linting pipeline when testing. Refactored the code to fit the spec

**Comment by AtzeDeVries** [comment]
@lacroi-m-insta  thanks for the contribution! will merge.

**Review by AtzeDeVries — APPROVED** [review]

**Pull request merged**
